In [1]:
# Importing Pandas library

import pandas as pd

In [2]:
# Create DataFrame with Missing Values

employee_dataframe = pd.DataFrame(
    {
        "Name": ["Rahul", "Priya", "Anuj"],
        "Age": [25, None, 29],
        "Salary": [30000, 40000, None]
    }
)

employee_dataframe

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya   NaN  40000.0
2   Anuj  29.0      NaN

In [3]:
# Detect Missing Values

employee_dataframe.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [4]:
# Calculate Mean Age

mean_age = employee_dataframe["Age"].mean()

print("Mean Age:", mean_age)

Mean Age: 27.0

In [5]:
# Replace Missing Age with Mean

employee_dataframe["Age"] = (
    employee_dataframe["Age"].fillna(mean_age)
)

employee_dataframe

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      NaN

In [6]:
# Replace Missing Salary with 0

employee_dataframe["Salary"] = (
    employee_dataframe["Salary"].fillna(0)
)

employee_dataframe

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      0.0