In [1]:
# Importing Pandas library

import pandas as pd

In [2]:
# Create Employee DataFrame

employee_dataframe = pd.DataFrame(
    {
        "Name": ["Rahul", "Priya", "Amit", "Anuj"],
        "Age": [25, 30, 28, 35],
        "Department": ["HR", "IT", "Finance", "IT"],
        "Salary": [30000, 50000, 45000, 60000]
    }
)

employee_dataframe

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000
2   Amit   28    Finance   45000
3   Anuj   35         IT   60000

In [3]:
# Show first 2 rows

employee_dataframe.head(2)

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000

In [4]:
# Show summary statistics

employee_dataframe.describe()

             Age   Salary
count   4.000000      4.0
mean   29.500000  46250.0
std     4.203173  12500.0
min    25.000000  30000.0
25%    27.250000  41250.0
50%    29.000000  47500.0
75%    31.250000  52500.0
max    35.000000  60000.0

In [5]:
# Display only IT employees

employee_dataframe[
    employee_dataframe["Department"] == "IT"
]

    Name  Age Department  Salary
1  Priya   30         IT   50000
3   Anuj   35         IT   60000

In [6]:
# Add Bonus column

employee_dataframe["Bonus"] = (
    employee_dataframe["Salary"] * 0.10
)

employee_dataframe

    Name  Age Department  Salary   Bonus
0  Rahul   25         HR   30000  3000.0
1  Priya   30         IT   50000  5000.0
2   Amit   28    Finance   45000  4500.0
3   Anuj   35         IT   60000  6000.0